import type { KilnController } from "../kiln-types.js";
import { PostModel, PostSchema } from "../models/post.js";

/**
 * Generated by "kiln generate controller". Each exported handler
 * maps to a route automatically — see CONVENTIONS.md section 2.
 */
const controller: KilnController = {
  async index(_req, res) {
    const records = await PostModel.findMany();
    res.json(records);
  },

  async show(req, res) {
    const record = await PostModel.findUnique({
      where: { id: Number(req.params.id) },
    });
    if (!record) return res.status(404).json({ error: "Not found" });
    res.json(record);
  },

  async create(req, res) {
    const parsed = PostSchema.safeParse(req.body);
    if (!parsed.success) {
      return res.status(422).json({ error: parsed.error.flatten() });
    }
    const record = await PostModel.create({ data: parsed.data });
    res.status(201).json(record);
  },

  async update(req, res) {
    const parsed = PostSchema.partial().safeParse(req.body);
    if (!parsed.success) {
      return res.status(422).json({ error: parsed.error.flatten() });
    }
    const record = await PostModel.update({
      where: { id: Number(req.params.id) },
      data: parsed.data,
    });
    res.json(record);
  },

  async destroy(req, res) {
    await PostModel.delete({ where: { id: Number(req.params.id) } });
    res.status(204).send();
  },
};

export default controller;
